package flightreservations.model;

/**
 * Model for {@link Airline} entities.
 * <p>
 * An airline operates many {@link Flight}s. It is stored in the
 * {@code airline} table of the database.
 * </p>
 *
 * @author Brayan
 * @author Ekaitz
 * @author Aritz
 */
public class Airline {
    /** The unique ID of the airline, assigned by the database. */
    private int airlineId;
    /** The name of the airline. */
    private String airlineName;
    /** The country of origin of the airline. */
    private String country;
    /** The two-character IATA code of the airline. */
    private String iataCode;

    /**
     * Constructs a new {@link Airline} that is not saved yet. The ID is
     * assigned by the database when it is inserted.
     *
     * @param airlineName the name of the airline
     * @param country     the country of origin of the airline
     * @param iataCode    the IATA code of the airline
     */
    public Airline(String airlineName, String country, String iataCode) {
        this.airlineName = airlineName;
        this.country = country;
        this.iataCode = iataCode;
    }

    /**
     * Constructs an {@link Airline} loaded from the database.
     *
     * @param airlineId   the unique ID of the airline
     * @param airlineName the name of the airline
     * @param country     the country of origin of the airline
     * @param iataCode    the IATA code of the airline
     */
    public Airline(int airlineId, String airlineName, String country, String iataCode) {
        this(airlineName, country, iataCode);
        this.airlineId = airlineId;
    }

    /**
     * Gets the {@link Airline}'s unique ID.
     *
     * @return the airline ID
     */
    public int getAirlineId() {
        return airlineId;
    }

    /**
     * Sets the {@link Airline}'s unique ID, as generated by the database.
     *
     * @param airlineId the airline ID
     */
    public void setAirlineId(int airlineId) {
        this.airlineId = airlineId;
    }

    /**
     * Gets the {@link Airline}'s name.
     *
     * @return the airline name
     */
    public String getAirlineName() {
        return airlineName;
    }

    /**
     * Sets the {@link Airline}'s name.
     *
     * @param airlineName the airline name
     */
    public void setAirlineName(String airlineName) {
        this.airlineName = airlineName;
    }

    /**
     * Gets the {@link Airline}'s country.
     *
     * @return the country of origin
     */
    public String getCountry() {
        return country;
    }

    /**
     * Sets the {@link Airline}'s country.
     *
     * @param country the country of origin
     */
    public void setCountry(String country) {
        this.country = country;
    }

    /**
     * Gets the {@link Airline}'s IATA code.
     *
     * @return the two-character IATA code
     */
    public String getIataCode() {
        return iataCode;
    }

    /**
     * Sets the {@link Airline}'s IATA code.
     *
     * @param iataCode the two-character IATA code
     */
    public void setIataCode(String iataCode) {
        this.iataCode = iataCode;
    }

    /**
     * Returns a pretty printed string of the {@link Airline} object.
     *
     * @return the airline as a multi-line string
     */
    @Override
    public String toString() {
        return "Airline {\n" +
                "  airlineId   : " + airlineId + "\n" +
                "  airlineName : " + airlineName + "\n" +
                "  country     : " + country + "\n" +
                "  iataCode    : " + iataCode + "\n" +
                "}";
    }
}
