package flightreservations.model;

/**
 * Model for {@link Customer} entities.
 * <p>
 * A customer is stored in the {@code customer} table of the database. The
 * {@code path} attribute points to the customer's bookings file, where the
 * flights booked by the customer are stored.
 * </p>
 *
 * @author Brayan
 * @author Ekaitz
 * @author Aritz
 */
public class Customer {
    /** The unique ID of the customer, assigned by the database. */
    private int customerId;
    /** The name of the customer. */
    private String customerName;
    /** The email address of the customer. */
    private String email;
    /** The phone number of the customer. */
    private String phoneNumber;
    /** The path of the customer's bookings file. */
    private String path;

    /**
     * Constructs a new {@link Customer} that is not saved yet. The ID and the
     * bookings file path are assigned when it is inserted.
     *
     * @param customerName the name of the customer
     * @param email        the email address of the customer
     * @param phoneNumber  the phone number of the customer
     */
    public Customer(String customerName, String email, String phoneNumber) {
        this.customerName = customerName;
        this.email = email;
        this.phoneNumber = phoneNumber;
    }

    /**
     * Constructs a {@link Customer} loaded from the database.
     *
     * @param customerId   the unique ID of the customer
     * @param customerName the name of the customer
     * @param email        the email address of the customer
     * @param phoneNumber  the phone number of the customer
     * @param path         the path of the customer's bookings file
     */
    public Customer(int customerId, String customerName, String email, String phoneNumber, String path) {
        this(customerName, email, phoneNumber);
        this.customerId = customerId;
        this.path = path;
    }

    /**
     * Gets the unique ID of the customer.
     *
     * @return the customer ID
     */
    public int getCustomerId() {
        return customerId;
    }

    /**
     * Sets the unique ID of the customer, as generated by the database.
     *
     * @param customerId the customer ID
     */
    public void setCustomerId(int customerId) {
        this.customerId = customerId;
    }

    /**
     * Gets the name of the customer.
     *
     * @return the customer name
     */
    public String getCustomerName() {
        return customerName;
    }

    /**
     * Sets the name of the customer.
     *
     * @param customerName the customer name
     */
    public void setCustomerName(String customerName) {
        this.customerName = customerName;
    }

    /**
     * Gets the email address of the customer.
     *
     * @return the email address
     */
    public String getEmail() {
        return email;
    }

    /**
     * Sets the email address of the customer.
     *
     * @param email the email address
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * Gets the phone number of the customer.
     *
     * @return the phone number
     */
    public String getPhoneNumber() {
        return phoneNumber;
    }

    /**
     * Sets the phone number of the customer.
     *
     * @param phoneNumber the phone number
     */
    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber;
    }

    /**
     * Gets the path of the customer's bookings file.
     *
     * @return the bookings file path, relative to the project root
     */
    public String getPath() {
        return path;
    }

    /**
     * Sets the path of the customer's bookings file.
     *
     * @param path the bookings file path, relative to the project root
     */
    public void setPath(String path) {
        this.path = path;
    }

    /**
     * Returns a pretty printed string of the {@link Customer} object.
     *
     * @return the customer as a multi-line string
     */
    @Override
    public String toString() {
        return "Customer {\n" +
                "  customerId   : " + customerId + "\n" +
                "  customerName : " + customerName + "\n" +
                "  email        : " + email + "\n" +
                "  phoneNumber  : " + phoneNumber + "\n" +
                "  path         : " + path + "\n" +
                "}";
    }
}
