package flightreservations.model;

import java.time.LocalDate;

/**
 * Model for {@link Flight} entities.
 * <p>
 * A flight is stored in the {@code flight} table of the database and is
 * operated by exactly one {@link Airline}.
 * </p>
 *
 * @author Brayan
 * @author Ekaitz
 * @author Aritz
 */
public class Flight {
    /** The unique ID of the flight, assigned by the database. */
    private int flightId;
    /** The origin city of the flight. */
    private String origin;
    /** The destination city of the flight. */
    private String destination;
    /** The departure date of the flight. */
    private LocalDate departureDate;
    /** The number of seats still available on the flight. */
    private int seatAmount;
    /** The travel class of the flight. */
    private TravelClass travelClass;
    /** The airline operating the flight. */
    private Airline airline;

    /**
     * Constructs a new {@link Flight} that is not saved yet. The ID is
     * assigned by the database and the airline is attached before saving.
     *
     * @param origin        the origin city of the flight
     * @param destination   the destination city of the flight
     * @param departureDate the departure date of the flight
     * @param seatAmount    the number of available seats on the flight
     * @param travelClass   the travel class of the flight
     */
    public Flight(String origin, String destination, LocalDate departureDate, int seatAmount,
            TravelClass travelClass) {
        this.origin = origin;
        this.destination = destination;
        this.departureDate = departureDate;
        this.seatAmount = seatAmount;
        this.travelClass = travelClass;
    }

    /**
     * Constructs a {@link Flight} loaded from the database.
     *
     * @param flightId      the unique ID of the flight
     * @param origin        the origin city of the flight
     * @param destination   the destination city of the flight
     * @param departureDate the departure date of the flight
     * @param seatAmount    the number of available seats on the flight
     * @param travelClass   the travel class of the flight
     * @param airline       the airline operating the flight
     */
    public Flight(int flightId, String origin, String destination, LocalDate departureDate, int seatAmount,
            TravelClass travelClass, Airline airline) {
        this(origin, destination, departureDate, seatAmount, travelClass);
        this.flightId = flightId;
        this.airline = airline;
    }

    /**
     * Gets the unique ID of the flight.
     *
     * @return the flight ID
     */
    public int getFlightId() {
        return flightId;
    }

    /**
     * Sets the unique ID of the flight, as generated by the database.
     *
     * @param flightId the flight ID
     */
    public void setFlightId(int flightId) {
        this.flightId = flightId;
    }

    /**
     * Gets the origin city of the flight.
     *
     * @return the origin city
     */
    public String getOrigin() {
        return origin;
    }

    /**
     * Sets the origin city of the flight.
     *
     * @param origin the origin city
     */
    public void setOrigin(String origin) {
        this.origin = origin;
    }

    /**
     * Gets the destination city of the flight.
     *
     * @return the destination city
     */
    public String getDestination() {
        return destination;
    }

    /**
     * Sets the destination city of the flight.
     *
     * @param destination the destination city
     */
    public void setDestination(String destination) {
        this.destination = destination;
    }

    /**
     * Gets the departure date of the flight.
     *
     * @return the departure date
     */
    public LocalDate getDepartureDate() {
        return departureDate;
    }

    /**
     * Sets the departure date of the flight.
     *
     * @param departureDate the departure date
     */
    public void setDepartureDate(LocalDate departureDate) {
        this.departureDate = departureDate;
    }

    /**
     * Gets the number of seats still available on the flight.
     *
     * @return the available seats
     */
    public int getSeatAmount() {
        return seatAmount;
    }

    /**
     * Sets the number of seats still available on the flight.
     *
     * @param seatAmount the available seats
     */
    public void setSeatAmount(int seatAmount) {
        this.seatAmount = seatAmount;
    }

    /**
     * Gets the travel class of the flight.
     *
     * @return the travel class
     */
    public TravelClass getTravelClass() {
        return travelClass;
    }

    /**
     * Sets the travel class of the flight.
     *
     * @param travelClass the travel class
     */
    public void setTravelClass(TravelClass travelClass) {
        this.travelClass = travelClass;
    }

    /**
     * Gets the airline operating the flight.
     *
     * @return the operating airline
     */
    public Airline getAirline() {
        return airline;
    }

    /**
     * Sets the airline operating the flight.
     *
     * @param airline the operating airline
     */
    public void setAirline(Airline airline) {
        this.airline = airline;
    }

    /**
     * Returns a pretty printed string of the {@link Flight} object.
     *
     * @return the flight as a multi-line string
     */
    @Override
    public String toString() {
        return "Flight {\n" +
                "  flightId      : " + flightId + "\n" +
                "  origin        : " + origin + "\n" +
                "  destination   : " + destination + "\n" +
                "  departureDate : " + departureDate + "\n" +
                "  seatAmount    : " + seatAmount + "\n" +
                "  travelClass   : " + travelClass + "\n" +
                "  airline       : " + (airline == null ? null : airline.getAirlineName()) + "\n" +
                "}";
    }
}
