package flightreservations.dao.impl;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.time.LocalDate;

import flightreservations.model.Airline;
import flightreservations.model.Customer;
import flightreservations.model.Flight;
import flightreservations.model.TravelClass;

/**
 * Converts JDBC results into model objects, so the mapping code is written
 * once and shared by all JDBC DAOs.
 *
 * @author Brayan
 * @author Ekaitz
 * @author Aritz
 */
final class ResultSetMapper {

    /** Utility class: not meant to be instantiated. */
    private ResultSetMapper() {
    }

    /**
     * Maps the current row to an {@link Airline}.
     *
     * @param resultSet a result set positioned on a row with the airline
     *                  columns
     * @return the airline in the current row
     * @throws SQLException if a column cannot be read
     */
    static Airline toAirline(ResultSet resultSet) throws SQLException {
        return new Airline(
                resultSet.getInt("airlineId"),
                resultSet.getString("airlineName"),
                resultSet.getString("country"),
                resultSet.getString("iataCode"));
    }

    /**
     * Maps the current row to a {@link Customer}.
     *
     * @param resultSet a result set positioned on a row with the customer
     *                  columns
     * @return the customer in the current row
     * @throws SQLException if a column cannot be read
     */
    static Customer toCustomer(ResultSet resultSet) throws SQLException {
        return new Customer(
                resultSet.getInt("customerId"),
                resultSet.getString("customerName"),
                resultSet.getString("email"),
                resultSet.getString("phoneNumber"),
                resultSet.getString("path"));
    }

    /**
     * Maps the current row to a {@link Flight}, including its airline.
     *
     * @param resultSet a result set positioned on a row with the flight and
     *                  airline columns
     * @return the flight in the current row
     * @throws SQLException if a column cannot be read
     */
    static Flight toFlight(ResultSet resultSet) throws SQLException {
        return new Flight(
                resultSet.getInt("flightId"),
                resultSet.getString("origin"),
                resultSet.getString("destination"),
                resultSet.getObject("departureDate", LocalDate.class),
                resultSet.getInt("seatAmount"),
                TravelClass.valueOf(resultSet.getString("travelClass")),
                toAirline(resultSet));
    }

    /**
     * Reads the key generated by the last insert of a statement created with
     * {@link Statement#RETURN_GENERATED_KEYS}.
     *
     * @param statement the statement that ran the insert
     * @return the generated key
     * @throws SQLException if no key was generated
     */
    static int toGeneratedKey(Statement statement) throws SQLException {
        try (ResultSet keys = statement.getGeneratedKeys()) {
            if (!keys.next()) {
                throw new SQLException("The database did not return a generated key.");
            }
            return keys.getInt(1);
        }
    }
}
